import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#fefae0',
  '--slot4-page-text': '#2e3420',
  '--slot4-panel-bg': '#fffaf0',
  '--slot4-surface-bg': '#fffef7',
  '--slot4-muted-text': '#6b724f',
  '--slot4-soft-muted-text': '#92977a',
  '--slot4-accent': '#626f47',
  '--slot4-accent-fill': '#a4b465',
  '--slot4-accent-soft': '#eef2d8',
  '--slot4-on-accent': '#fefae0',
  '--slot4-dark-bg': '#23261d',
  '--slot4-dark-text': '#fefae0',
  '--slot4-media-bg': '#d7dcbf',
  '--slot4-cream': '#fefae0',
  '--slot4-warm': '#fff7d7',
  '--slot4-lavender': '#f4f1dc',
  '--slot4-gray': '#f2efd9',
  '--slot4-body-gradient': 'radial-gradient(circle at top left, rgba(255, 207, 80, 0.22), transparent 28%), linear-gradient(180deg, rgba(254, 250, 224, 1) 0%, rgba(250, 245, 214, 1) 100%)',
  '--editable-page-bg': '#fefae0',
  '--editable-page-text': '#2e3420',
  '--editable-container': '1480px',
  '--editable-border': 'rgba(98, 111, 71, 0.16)',
  '--editable-nav-bg': 'rgba(35, 38, 29, 0.88)',
  '--editable-nav-text': '#fefae0',
  '--editable-nav-active': '#ffcf50',
  '--editable-nav-active-text': '#23261d',
  '--editable-cta-bg': '#a4b465',
  '--editable-cta-text': '#23261d',
  '--editable-search-bg': '#fffef7',
  '--editable-footer-bg': '#23261d',
  '--editable-footer-text': '#fefae0',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_18px_40px_rgba(54,61,38,0.10)]',
  shadowStrong: 'shadow-[0_28px_72px_rgba(25,28,19,0.22)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(35,38,29,0.04),rgba(35,38,29,0.78))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.28em] text-[var(--slot4-accent-fill)]',
    heroTitle: 'text-4xl font-semibold leading-[1.02] tracking-[-0.04em] sm:text-5xl lg:text-[3.6rem]',
    sectionTitle: 'text-3xl font-semibold tracking-[-0.03em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[1.75rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.75rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.75rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[#23261d] transition duration-200 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent-fill)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-bold text-[#23261d] transition duration-200 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.5rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_24px_56px_rgba(36,40,27,0.16)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
